# Generated by Django 3.0.5 on 2020-11-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='uuid',
            new_name='UUID',
        ),
    ]
